---
application_name: magento2
base_url: http://192.168.33.10

# MySQL parameters
mysql_user: magento2
mysql_password: magento2
mysql_dbname: magento2

# Composer auth.json parameters
github_token: your_github_token_here
magento_account_public_key: your_public_key_here
magento_account_private_key: your_private_key_here

# Magento install parameters
magento2_language: en_US
magento2_currency: USD
magento2_admin_user: admin
magento2_admin_password: admin2015
magento2_admin_email: admin@myfakedomain.com
magento2_admin_firstname: John
magento2_admin_lastname: Doe
