---
- name: Download installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /home/vagrant/composer-setup.php
    checksum: "sha384:669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410"

- name: Install
  become: true
  shell: php /home/vagrant/composer-setup.php --filename=composer --install-dir=/usr/local/bin

- name: Delete installer
  file: path=/home/vagrant/composer-setup.php state=absent
